const courses = [
    {
      className: "Accounting 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Accounting 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Activism and Social Justice Literature",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advertising",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced 3D Art: Levels 2–8",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced 4D Art & Animation: Levels 2–8",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Animal Science",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Ceramics: Levels 2–7",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Chemistry",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Creative Writing",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Drawing, Painting, Printmaking: Levels 2–7",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Graphic Design: Levels 2–8",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Jewelry: Levels 2–7",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Manufacturing and Welding",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Advanced Photography: Levels 2–8",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP Biology",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP Chemistry",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP English Language & Composition",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP English Literature & Composition",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP European History",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP Physics",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP Psychology",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP U.S. Government & Politics",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP U.S. History",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "AP Calculus (AB)",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Algebra 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Algebra 1AB",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Algebra 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "American Literature",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "American Society Through Film",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Animal Science",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Applied Sciences, Technology, Engineering & Manufacturing",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Architectural CADD Drafting",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Aquatics",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Art Club",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Business and Personal Law",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Business Engagement Collaborative",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Basic Composition",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Carpentry 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Carpentry 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Ceramics I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Chamber Orchestra",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Child Development I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Child Development II",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Computer-Aided Manufacturing",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Concert Band",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Concert Choir",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Concert Chorale",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Creative Writing",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Culinary Arts",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Drama",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Drawing, Painting, Printmaking I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Early Childhood Education I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Early Childhood Education II",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Early Childhood Education III - Field Experience",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Earth and Space Science",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Economics",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "ELP Independent Study",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Engineering CADD Drafting",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "English 9 Literature",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "English 9 Workshop",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Entrepreneurship 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Entrepreneurship 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Entrepreneurship 3 / Start-Up",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Government & Civic Literacy",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Literacy 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Literacy 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Literacy 3",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Literacy 4",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Math 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Math 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Math 3",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Math 4",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Science of Earth Systems",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Science of Life Systems",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential Science of Physical Systems",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential U.S. History",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Essential World Studies",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Experienced-Based Career Skill Development",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Foundations of 2-Dimensional Art",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Foundations of 3-Dimensional Art",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Foundations of 4D Art & Animation",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Food Science and Safety",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Food, Ecosystems & Community: A Greenhouse Approach",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "French 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "French 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "French 3",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "French 4",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Freshman Band",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Freshman Choir",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Freshman Orchestra",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Geometry",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Geometry AB",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "German 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "German 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "German 3",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "German 4",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Graphic Design I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Health",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Heritage Spanish",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Honors World Studies",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Horror Literature",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Independent Studio",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Innovation Fitness: Individual Performance PE",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Information Computing",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Internship Program 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Internship Program 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Introduction to Agriscience",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Introduction to Business",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Introduction to Carpentry",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Introduction to Human Services",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Introduction to Journalism",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Introduction to Manufacturing",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Jewelry I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Lifeguarding / WSI",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Lifespan Nutrition & Wellness",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Manufacturing and Welding",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Marketing and Selling",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Math Lab",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Microsoft Certification",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Multimedia Composition",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Mythology, Fantasy, & Folklore",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Natural Resources",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Non-Western World",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Outdoor Recreation",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Personal Development 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Personal Development 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Personal Finance",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Photography I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Physical Science",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Physics",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Plant Science",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Pre-Calculus",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Science Senior Capstone",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Shakespeare",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Sheltered Algebra 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Sheltered English (ELD) 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Sheltered English (ELD) 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Social Skills",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Sociology",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Spanish 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Spanish 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Spanish 3",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Spanish 4",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Speech",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Statistics",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Survey of Literature (10th)",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Survey of Literature (12th)",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Symphony Orchestra",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Team Games / Sports",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Teacher Academy",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Twirler",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "U.S. Government",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "U.S. History",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Unified Physical Education",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Video Production",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Web Design",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Weights I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Weights II",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Western Civilization I",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Western Civilization II",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Wind Symphony / Symphonic Band",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Woodworking 1",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Woodworking 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "World Issues",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "World Literature 2",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "World Studies",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    },
    {
      className: "Yearbook (SPIRIT)",
      dualCredit: false,
      subject: "General",
      prerequisite: null,
      duration: "semester",
      honorsAP: "none",
      description: "Description pending.",
      averageGrade: 85,
      ratings: [4, 5, 3],
      comments: ["Good class", "Challenging but fun"],
      averageTimePerWeek: 3,
      icon: "📘"
    }
    ];



const courseNames = [
    "Accounting 1",
    "Accounting 2",
    "Activism and Social Justice Literature",
    "Advertising",
    "Advanced 3D Art: Levels 2–8",
    "Advanced 4D Art & Animation: Levels 2–8",
    "Advanced Animal Science",
    "Advanced Ceramics: Levels 2–7",
    "Advanced Chemistry",
    "Advanced Creative Writing",
    "Advanced Drawing, Painting, Printmaking: Levels 2–7",
    "Advanced Graphic Design: Levels 2–8",
    "Advanced Jewelry: Levels 2–7",
    "Advanced Manufacturing and Welding",
    "Advanced Photography: Levels 2–8",
    "AP Biology",
    "AP Chemistry",
    "AP English Language & Composition",
    "AP English Literature & Composition",
    "AP European History",
    "AP Physics",
    "AP Psychology",
    "AP U.S. Government & Politics",
    "AP U.S. History",
    "AP Calculus (AB)",
    "Algebra 1",
    "Algebra 1AB",
    "Algebra 2",
    "American Literature",
    "American Society Through Film",
    "Animal Science",
    "Applied Sciences, Technology, Engineering & Manufacturing",
    "Architectural CADD Drafting",
    "Aquatics",
    "Art Club",
    "Business and Personal Law",
    "Business Engagement Collaborative",
    "Basic Composition",
    "Carpentry 1",
    "Carpentry 2",
    "Ceramics I",
    "Chamber Orchestra",
    "Child Development I",
    "Child Development II",
    "Computer-Aided Manufacturing",
    "Concert Band",
    "Concert Choir",
    "Concert Chorale",
    "Creative Writing",
    "Culinary Arts",
    "Drama",
    "Drawing, Painting, Printmaking I",
    "Early Childhood Education I",
    "Early Childhood Education II",
    "Early Childhood Education III - Field Experience",
    "Earth and Space Science",
    "Economics",
    "ELP Independent Study",
    "Engineering CADD Drafting",
    "English 9 Literature",
    "English 9 Workshop",
    "Entrepreneurship 1",
    "Entrepreneurship 2",
    "Entrepreneurship 3 / Start-Up",
    "Essential Government & Civic Literacy",
    "Essential Literacy 1",
    "Essential Literacy 2",
    "Essential Literacy 3",
    "Essential Literacy 4",
    "Essential Math 1",
    "Essential Math 2",
    "Essential Math 3",
    "Essential Math 4",
    "Essential Science of Earth Systems",
    "Essential Science of Life Systems",
    "Essential Science of Physical Systems",
    "Essential U.S. History",
    "Essential World Studies",
    "Experienced-Based Career Skill Development",
    "Foundations of 2-Dimensional Art",
    "Foundations of 3-Dimensional Art",
    "Foundations of 4D Art & Animation",
    "Food Science and Safety",
    "Food, Ecosystems & Community: A Greenhouse Approach",
    "French 1",
    "French 2",
    "French 3",
    "French 4",
    "Freshman Band",
    "Freshman Choir",
    "Freshman Orchestra",
    "Geometry",
    "Geometry AB",
    "German 1",
    "German 2",
    "German 3",
    "German 4",
    "Graphic Design I",
    "Health",
    "Heritage Spanish",
    "Honors World Studies",
    "Horror Literature",
    "Independent Studio",
    "Innovation Fitness: Individual Performance PE",
    "Information Computing",
    "Internship Program 1",
    "Internship Program 2",
    "Introduction to Agriscience",
    "Introduction to Business",
    "Introduction to Carpentry",
    "Introduction to Human Services",
    "Introduction to Journalism",
    "Introduction to Manufacturing",
    "Jewelry I",
    "Lifeguarding / WSI",
    "Lifespan Nutrition & Wellness",
    "Manufacturing and Welding",
    "Marketing and Selling",
    "Math Lab",
    "Microsoft Certification",
    "Multimedia Composition",
    "Mythology, Fantasy, & Folklore",
    "Natural Resources",
    "Non-Western World",
    "Outdoor Recreation",
    "Personal Development 1",
    "Personal Development 2",
    "Personal Finance",
    "Photography I",
    "Physical Science",
    "Physics",
    "Plant Science",
    "Pre-Calculus",
    "Science Senior Capstone",
    "Shakespeare",
    "Sheltered Algebra 1",
    "Sheltered English (ELD) 1",
    "Sheltered English (ELD) 2",
    "Social Skills",
    "Sociology",
    "Spanish 1",
    "Spanish 2",
    "Spanish 3",
    "Spanish 4",
    "Speech",
    "Statistics",
    "Survey of Literature (10th)",
    "Survey of Literature (12th)",
    "Symphony Orchestra",
    "Team Games / Sports",
    "Teacher Academy",
    "Twirler",
    "U.S. Government",
    "U.S. History",
    "Unified Physical Education",
    "Video Production",
    "Web Design",
    "Weights I",
    "Weights II",
    "Western Civilization I",
    "Western Civilization II",
    "Wind Symphony / Symphonic Band",
    "Woodworking 1",
    "Woodworking 2",
    "World Issues",
    "World Literature 2",
    "World Studies",
    "Yearbook (SPIRIT)"
  ];
  